name: Terraform Destroy - iBurguer

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment:
      name: Iburguer

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.4

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve -var="mongodbatlas_public_key=${{ secrets.ATLAS_PUBLIC_KEY }}" -var="mongodbatlas_private_key=${{ secrets.ATLAS_PRIVATE_KEY }}"
